- zht/cards.json
> Higher priority changefix

- zht/cards.json
https://zh.wikipedia.org/wiki/%E7%99%BD%E9%9B%9C%E8%A8%8A
> Replace "白色雜訊" with "白雜訊", due to its formal name according to wiki

- .travis.yml
- localization/validate_localization.py
To validate json format and compare json item with "eng".
Outside "zht" folder will be rename to "new" folder in validation.
> Integrate travis ci

- zht/cards.json
- zht/ui.json
- Update "Offering" 
- Update "SaveSlotScreen"
> Localize "(08-07-2018) BETA"

- zht/credits.json
> Localize version "(08-08-2018) BETA"

- zht/events.json
Update notes
```
08-21-2018
events.json
"Colosseum"
This is a new event
```
zht
- Update new event "Colosseum"
> Localize "(08-21-2018) BETA"

- zht/characters.json
- zht/run_mods.json
Update notes
```
09-25-2018
run_mods.json
"SealedDeck"
"IntelligentEnemies"
"MonsterHunter"
"NeowTime"
"Flight"
"ControlledChaos"
"Careless"
"Chimera"
"DeadlyEvents"
characters.json
"Neow Event"
"OPTIONS"
"Choose 10 cards to add to your deck."
```
```
"DESCRIPTION": "Start with 5 copies of a single rare card."
->
"DESCRIPTION": "Start with 5 copies of a single card."
```
> Localize "(09-25-2018) BETA"

- zht/ui.json
Update note
```
10-30-2018
ui.json
"BetaArtUnlockEffect": {
"Ironclad Beta Card Art Unlocked!",
"The Silent Beta Card Art Unlocked!",
"Defect Beta Card Art Unlocked!",
"All Beta Card Art Unlocked!"
```
> Localize "(10-30-2018) BETA"

- zht/credits.json
- zht/powers.json
Update note
```
11-02-2018
powers.json
"Invincible"
" more HP this round.",
"Can no longer be harmed this round."
credits.json
"LOC_RUS"
"Dmitry \"Regallion\" Zhiryakov",
"Suggestions and Feedback:",
->
"Dmitry \"Regallion\" Zhiryakov",
"Dmitry \"Gentle Giant\" Gitsman",
"Neprim",
"Suggestions and Feedback:",
```
> Localize "(11-02-2018) BETA"

- zht/credits.json
- zht/run_mods.json
Update note
```
11-05-2018
run_mods.json
"The Ending"
"NAME": "The Ending",
"DESCRIPTION": "Enables the Final Act."
credits.json
"LOC_ZHS"
"IrisRaphael"
potions.json
"SneckoOil"
" Become #yConfused. Draw #b",
->
"Become #yConfused. Draw #b",
```
> Localize "(11-05-2018) BETA"

- zht/ui.json
Update notes
```
12-30-2018
ui.json
"RunHistoryPathNodes"
"#bRecalled"
```
```
12-31-2018
credits.json
"SPECIAL"
"Tony \"kiooeht\" Moore"
"TEST"
"Jason \"Wyrm\" Deng",
"Jonas \"bigunit3000\" Wilson",
"TBytemaster"
```
> Localize version "(01-01-2019) Beta"

- zht/ui.json
Update note
```
01-09-2019
ui.json
"RichPresence"
"Daily - Floor %s",
"Custom - Floor %s",
" - Floor %s",
"Main Menu"
```
> Localize "(01-09-2019) BETA"

- zht/ui.json
Update notes
```
05-23-2019
ui.json
"BetterToHandAction"
"CardLibSortHeader"
"Obtained"
events.json
"Vampires"
"% #rMax #rHP.",
"Ghosts"
"% #rMax #rHP.",
```
> Localize version "(05-24-2019) BETA"

- zht/credits.json
Update notes
```
05-29-2019
credits.json
"PUBLISHING"
"PORTING"
```
> Localize "(05-28-2019) BETA"

- zht/ui.json
Update note
```
06-07-2019
ui.json
"InputSettingsScreen"
"Touchscreen Mode"
```
> Localize version "(06-07-2019) BETA"

- zht/ui.json
update note
```
07-10-2019
ui.json
"MiscConsoleStrings"
"Press ",
" to Start"
"Switch Profile"
```
> Localize version "(07-10-2019) BETA"

- zhs2zht/stances.json
- zht/cards.json
- zht/potions.json
- zht/relics.json
Update notes
```
09-09-2019
potions.json
"AttackPotion"
"SkillPotion"
"PowerPotion"
"DuplicationPotion"
```
> Localize (09-09-2019v2) BETA

- zht/cards.json
- zht/credits.json
- zht/potions.json
- zht/powers.json
Update note
```
09-12-2019
potions.json
"SneckoOil"
"Become #yConfused. Draw #b",
" cards.",
"card."
->
"Draw #b",
" cards. Randomize the cost of cards in your hand.",
""
cards.json
"ClearTheMind"
RENAME: "Clear the Mind" -> "Tranquility"
"DESCRIPTION": "Enter Calm. NL Exhaust."
->
"DESCRIPTION": "Retain. NL Enter Calm. NL Exhaust."
"Worship"
"UPGRADE_DESCRIPTION": "Innate. NL Gain !M! Mantra."
->
"UPGRADE_DESCRIPTION": "Retain. NL Gain !M! Mantra."
"Judgement"
"NAME": "Judgement",
->
"NAME": "Judgment",
powers.json
"Controlled"
"NAME"
"Controlled",
->
"NAME": "Mental Fortress",
"WireheadingPower"
"At the start of your turn, #yScry #b",
"."
```
> Localize "(09-12-2019) BETA)"

- zht/cards.json
- zht/powers.json
Update note
```
09-16-2019
cards.json
"SashWhip"
"Judgement" (Key remains the same)
"NAME": "Judgement",
->
"NAME": "Judgment",
"PathToVictory"
"DESCRIPTION": "Draw a card and reduce its cost to 0 this turn. NL Exhaust.",
"UPGRADE_DESCRIPTION": ""
->
"DESCRIPTION": "Play the top card of your draw pile. NL Exhaust.",
"UPGRADE_DESCRIPTION": "Play the top card of your draw pile."
"Wireheading"
-"NAME": "Wireheading",
->
"NAME": "Foresight",
"TalkToTheHand"
"DESCRIPTION": "Deal !D! damage. NL Whenever this enemy takes damage, gain !M! Block. NL Exhaust."
->
"DESCRIPTION": "Deal !D! damage. NL Whenever you attack this enemy, gain !M! Block. NL Exhaust."
"Establishment"
"DESCRIPTION": "Whenever a card is Retained, lower its cost by !M!.",
"UPGRADE_DESCRIPTION": "Innate. NL Whenever a card is …
```
> Localize "(09-17-2019) BETA"

- localization/UPDATES.txt
- localization/eng/cards.json
- localization/eng/potions.json
- localization/eng/powers.json
- localization/zhs/cards.json
- localization/zhs/powers.json
- localization/zht/cards.json
- localization/zht/powers.json
- zhs2zht/cards.json
- zhs2zht/powers.json
- zht/cards.json
- zht/potions.json
- zht/powers.json
Update note
```
09-20-2019
cards.json
"Adaptation"
"UPGRADE_DESCRIPTION": "Innate. NL Whenever you switch Stances, draw !M! card."
->
"UPGRADE_DESCRIPTION": "Deprecated."
"MasterReality"
"DESCRIPTION": "Choose NL *Smite or *Safety. NL At the start of each turn add the chosen card into your hand."
->
"DESCRIPTION": "At the end of your turn, deal !M! damage to a random enemy for each Retained card in your hand."
"BattleHymn"
"DESCRIPTION": "The first card you draw each turn has its cost reduced by !M! for the turn."
->
"DESCRIPTION": "At the start of each turn add a *Smite into your hand.",
"UPGRADE_DESCRIPTION": "At the start of each turn add !M! *Smites into your hand."
"Brilliance"
"DESCRIPTION": "Heal !M! HP X times. NL Exhaust.",
->
"DESCRIPTION": "Ethereal. NL Heal !M! HP X times. NL …
```
> Localize "(09-19-2019) BETA"

- localization/UPDATES.txt
- localization/eng/cards.json
- localization/eng/powers.json
- localization/eng/relics.json
- localization/zhs/cards.json
- localization/zhs/relics.json
- localization/zht/cards.json
- localization/zht/relics.json
- zhs2zht/cards.json
- zhs2zht/relics.json
- zht/cards.json
- zht/powers.json
- zht/relics.json
Update note
```
09-26-2019
cards.json
"Omniscience"
"DESCRIPTION": "Whenever you Scry, Scry !M! additional cards.",
->
"DESCRIPTION": "Choose a card in your draw pile. NL Play the chosen card twice and exhaust it. NL Exhaust.",
"Pray"
"DESCRIPTION": "Gain !M! Mantra. NL Shuffle a *Miracle into your draw pile.",
"UPGRADE_DESCRIPTION": "Gain !M! Mantra. NL Shuffle an Upgraded *Miracle into your draw pile."
->
"DESCRIPTION": "Gain !M! Mantra. NL Shuffle an *Insight into your draw pile.",
"UPGRADE_DESCRIPTION": "Gain !M! Mantra. NL Shuffle an Upgraded *Insight into your draw pile."
"Adaptation" (Aka Rushdown)
"DESCRIPTION": "Whenever you enter Wrath, draw !M! card.",
"UPGRADE_DESCRIPTION": "Deprecated."
->
"DESCRIPTION": "Whenever you enter Wrath, draw !M! cards.",
"UPGRADE_DESCRIPTION": …
```
> Localize "(09-25-2019) BETA"

- localization/UPDATES.txt
- localization/eng/cards.json
- localization/eng/potions.json
- localization/eng/powers.json
- localization/zhs/cards.json
- localization/zhs/powers.json
- localization/zht/cards.json
- localization/zht/powers.json
- zhs2zht/cards.json
- zhs2zht/powers.json
- zht/cards.json
- zht/potions.json
- zht/powers.json
Update note
```
09-30-2019
cards.json
"Fasting2"
"WaveOfTheHand2"
"Tantrum"
"DESCRIPTION": "Deal !D! damage to a random enemy !M! times. NL Enter Wrath. NL Shuffle this card into your draw pile."
->
"DESCRIPTION": "Deal !D! damage NL !M! times. NL Enter Wrath. NL Shuffle this card into your draw pile."
"Fasting"
"NAME": "Fasting",
"DESCRIPTION": "Gain !M! Artifact."
->
"NAME": "Fasting A",
"DESCRIPTION": "Gain !M! Strength. NL Gain !M! Dexterity."
"WaveOfTheHand"
"NAME": "Wave of the Hand",
"DESCRIPTION": "Whenever you gain Block this turn, apply !M! Weak and !M! Vulnerable to ALL enemies."
->
"NAME": "Wave of the Hand B",
"DESCRIPTION": "Whenever you gain Block this turn, apply !M! Weak to ALL enemies."
"Wish"
"DESCRIPTION": "Lose 25% of your current HP. NL Makes your dreams come true. …
```
> Localize "localization09302019.zip"

- localization/UPDATES.txt
- localization/eng/cards.json
- localization/eng/powers.json
- localization/zhs/cards.json
- localization/zhs/powers.json
- localization/zht/cards.json
- localization/zht/powers.json
- zhs2zht/cards.json
- zhs2zht/powers.json
- zht/cards.json
- zht/powers.json
Update note
```
10-09-2019
cards.json
"Study"
"LikeWater"
"PathToVictory"
"DESCRIPTION": "Whenever you play *Path *to *Victory, this enemy loses !M! HP.",
->
"DESCRIPTION": " Apply !M! *Mark. NL ALL enemies lose HP equal to their *Mark.",
"FlowState"
"NAME": "Flow State",
->
"NAME": "DEPRECATED Flow State",
"Discipline"
"NAME": "Discipline",
->
"NAME": "DEPRECATED Discipline",
powers.json
"Study"
"LikeWaterPower"
"PathToVictoryPower"
"NAME": "Path to Victory",
->
"NAME": "Mark",
"DisciplinePower"
"NAME": "Discipline",
->
"NAME": "DEPRECATED Discipline",
```
> Localize localization10092019v2.zip

- localization/UPDATES.txt
- localization/eng/cards.json
- localization/eng/keywords.json
- localization/eng/potions.json
- localization/eng/powers.json
- localization/zhs/keywords.json
- localization/zhs/potions.json
- localization/zhs/powers.json
- localization/zht/keywords.json
- localization/zht/potions.json
- localization/zht/powers.json
- zhs2zht/keywords.json
- zhs2zht/potions.json
- zhs2zht/powers.json
- zht/keywords.json
- zht/potions.json
- zht/powers.json
Update note
```
10-14-2019
cards.json
"Halt"
"DESCRIPTION": "Gain !B! Block. NL Wrath: Gain !M! additional Block."
->
"DESCRIPTION": "Gain !B! Block. NL If you are in Wrath, gain !M! additional Block."
keywords.json
"RITUAL"
potions.json
"CultistPotion"
"LiquidMemories"
"DistilledChaos"
powers.json
"Ritual"
"At the end of your turn, gain #b"
```
> Localize localization10142019.zip

- localization/UPDATES.txt
- localization/eng/potions.json
- localization/zhs/potions.json
- localization/zht/potions.json
- zhs2zht/potions.json
- zht/potions.json
Update note
```
10-23-2019
potions.json
"Colorless Potion"
"BlessingOfTheForge"
```
> Localize localization10232019.zip

- localization/UPDATES.txt
- localization/eng/cards.json
- localization/zhs/cards.json
- localization/zht/cards.json
- zhs2zht/cards.json
- zht/cards.json
Update note
```
10-29-2019
cards.json
"Brilliance"
"DESCRIPTION": "Ethereal. NL Heal !M! HP X times. NL Exhaust.",
->
"DESCRIPTION": "Deal !D! damage for each unique Stance entered this combat.",
"EXTENDED_DESCRIPTION": [
""
]
->
"EXTENDED_DESCRIPTION": [
" NL (Entered !M! Stance.)",
" NL (Entered !M! Stances.)"
]
----------------------------------
10-28-2019
cards.json
"BattleHymn" (Typo)
"DESCRIPTION": "At the start of each turn add a *Smite into your hand.",
"UPGRADE_DESCRIPTION": "Innate. NL At the start of each turn add a *Smite into your hand."
->
"DESCRIPTION": "At the start of each turn, add a *Smite into your hand.",
"UPGRADE_DESCRIPTION": "Innate. NL At the start of each turn, add a *Smite into your hand."
```
> Localize localization10292019.zip
